stages:
    - mirror
    - test

.composer_cache: &composer_cache
    cache:
        paths:
            - vendor/

.composer_install: &composer_install
    before_script:
        - curl -sS https://getcomposer.org/installer | php
        - php composer.phar install --prefer-dist --classmap-authoritative --no-interaction --no-progress

.composer_test: &composer_test
    script:
        - php composer.phar test

github:
    before_script:
        - apk add --update --no-cache bash git openssh
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
        - ssh-keyscan github.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
        - bash -c "ssh-add <(echo '$SSH_GITHUB_GITLAB')"

    image: alpine:latest
    stage: mirror
    script:
        - git push --mirror git@github.com:ThePixelDeveloper/Sitemap.git

php 7.0:
    image: php:7.0-alpine
    stage: test
    <<: *composer_install
    <<: *composer_test
    <<: *composer_cache

php 7.1:
    image: php:7.1-alpine
    stage: test
    <<: *composer_install
    <<: *composer_test
    <<: *composer_cache

php 7.2:
    image: php:7.2-rc-alpine
    stage: test
    <<: *composer_install
    <<: *composer_test
    <<: *composer_cache
